"""Build an importable full-tunnel profile from a verified local identity."""

import hashlib
import ipaddress
import re

from .keys import validate_key


class ProfileError(Exception):
    """Profile inputs are missing or inconsistent."""


def build_profile(identity: dict, settings: dict, dns: str, endpoint: str | None = None) -> str:
    registration = settings.get("registration")
    if not isinstance(registration, dict):
        raise ProfileError("No enrollment results found. Run vpnctl enroll first.")
    if registration.get("public_key") != identity["public_key"]:
        raise ProfileError("Enrollment belongs to a different local identity. Run vpnctl enroll again.")
    server_key = registration.get("server_public_key")
    validate_key(server_key)
    try:
        address = ipaddress.ip_interface(registration["address"])
        subnet = ipaddress.ip_network(registration["subnet"])
        if address.version != 4 or address.network.prefixlen != 32 or address.ip not in subnet:
            raise ValueError
    except (KeyError, TypeError, ValueError):
        raise ProfileError("Invalid enrolled address or subnet. Run vpnctl enroll again.") from None
    port = registration.get("listen_port")
    if type(port) is not int or not 1 <= port <= 65535:
        raise ProfileError("Invalid enrolled WireGuard port.")
    host = endpoint if endpoint is not None else settings.get("host")
    if not isinstance(host, str) or not host:
        raise ProfileError("A public server hostname or IP is required.")
    try:
        ip = ipaddress.ip_address(host)
        host = f"[{ip}]" if ip.version == 6 else str(ip)
    except ValueError:
        if len(host) > 253 or not all(re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?", label)
                                      for label in host.rstrip(".").split(".")):
            raise ProfileError("Endpoint must be a hostname or IP without a port or URL prefix.") from None
    try:
        resolvers = [ipaddress.ip_address(value.strip()) for value in dns.split(",")]
        if not resolvers or any(ip.version != 4 or ip.is_unspecified or ip.is_multicast or ip.is_loopback for ip in resolvers):
            raise ValueError
    except ValueError:
        raise ProfileError("Enter comma-separated IPv4 DNS server addresses reachable through the VPN.") from None

    # Give macOS an IPv6 tunnel address so ::/0 has an IPv6 interface to use.
    # This local ULA is deliberately NOT registered server-side: IPv6 traffic
    # routed into this tunnel is rejected by the IPv4-only peer assignment.
    digest = hashlib.sha256(identity["public_key"].encode("ascii")).digest()
    blocked_ipv6 = ipaddress.IPv6Address(b"\xfd" + digest[:15])
    return (
        "# Generated by vpnctl. Contains a private key; keep this file private.\n"
        "# IPv6 is captured by this tunnel but not enabled on the server peer.\n"
        "[Interface]\n"
        f"PrivateKey = {identity['private_key']}\n"
        f"Address = {address}, {blocked_ipv6}/128\n"
        f"DNS = {', '.join(str(ip) for ip in resolvers)}\n\n"
        "[Peer]\n"
        f"PublicKey = {server_key}\n"
        f"Endpoint = {host}:{port}\n"
        "AllowedIPs = 0.0.0.0/0, ::/0\n"
        "PersistentKeepalive = 25\n"
    )
